name: Generate android keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore moyu.jks -storepass moyu-ks-2026 -keypass moyu-ks-2026 \
            -alias moyu -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Moyu, O=aiastia, C=CN"
          base64 -w0 moyu.jks > moyu.jks.b64
      - uses: actions/upload-artifact@v4
        with:
          name: android-keystore
          path: |
            moyu.jks
            moyu.jks.b64
          retention-days: 1
